name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12', '3.13']
                test-level: ['unit', 'integration', 'system']
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip wheel
                pip install -e ".[dev]"
            - name: Quick CLI Smoke Test
              run: |
                units-convert --help || (echo "CLI missing" && exit 1)
            - name: Run Tests
              run: |
                pytest tests/${{ matrix.test-level }}
    test-complete:
        name: test
        needs: test
        runs-on: ubuntu-latest

        if: always()

        steps:
            - name: Fail if any matrix job failed
              run: |
                if [[ "${{ needs.test.result }}" != "success" ]]; then
                    echo "Some matrix jobs failed"
                    exit 1
                fi